# Generated by Pegasus transpiler


class Calculator:
    self.mesage = m
    print(m)

    def __init__(self):
    t0 = x + y
    r = t0
    return r

    def add$ii(self):


calc = Calculator("Hello")
t1 = calc.add$ii(5, 6)
result = t1
print(result)
