# Generated by Pegasus transpiler


def binarySearch_i(tgt):
    l_0 = 0
    r_0 = 4
    t0 = l_0 < r_1
    while l_0 < r_1:
        t1 = l_0 + r_1
        t2 = t1 // 2
        mid = t2
        t3 = mid_2 * 4
        t4 = arr[t3]
        t5 = t4 == tgt
        if t4 == tgt:
            return mid_2
        else:
            t6 = mid_2 * 4
            t7 = arr[t6]
            t8 = t7 < tgt
            if t7 < tgt:
                t9 = mid_2 + 1
                l_0 = t9
            else:
                t10 = mid_2 - 1
                r_1 = t10
    t11 = 0 - 1
    return t11

target = 1
t12 = binarySearch_i(target)
res = t12
print(res)
