# Generated by Pegasus transpiler


def mul_ii(x, y):
    t0 = x * y
    return t0

sum = self
i$0 = 1
t1 = i$0 < 5
while i$0 < 5:
    t3 = i$0 + 1
    t4 = i$0 * t3
    t5 = sum + t4
    sum = t5
    t2 = i$0 + 1
    i$0 = t2
print(sum)
